# Generated by Django 4.1.3 on 2022-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='emailingizni kiriting', max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(help_text='telefon raqamingizni kiriting', max_length=150, verbose_name='phone number')),
                ('location', models.CharField(help_text='joylashuvingizni kiriting', max_length=150, verbose_name='joylashuv')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ismingizni kiriting', max_length=150, verbose_name='Ismingiz')),
                ('image', models.ImageField(help_text='rasmingizni yuklang', upload_to='profil_image', verbose_name='Rasmingiz')),
                ('age', models.IntegerField(help_text='yoshingizni kiriting', verbose_name='Age')),
                ('techlonoligies', models.TextField(help_text='ishlatgan texnologiyalaringizni kiriting ', verbose_name='Technologies')),
                ('jop', models.CharField(help_text='kasbingizni kiriting ', max_length=150, verbose_name='Jop')),
                ('languages', models.CharField(default='Uzbek', help_text='yana boshqa tillarni bilsangiz kiriting', max_length=150, verbose_name='Language')),
                ('qilingan_ish', models.FileField(help_text='rezumengizni yuklang', upload_to='resumes', verbose_name='Resumes')),
                ('profession_years', models.IntegerField(default='1.5', help_text='tajribangizni kiriting', verbose_name='ish tajribasi')),
                ('projects', models.IntegerField(help_text='qilgan ishlaringizni kiriting ', verbose_name='loyihalar')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='loyiha nomini kiriting', max_length=150, verbose_name='Title')),
                ('loyiha_url', models.URLField(help_text='loyiha url kiriting ', verbose_name='URL')),
                ('images', models.ImageField(upload_to='loyiha_images', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(default='https://me.@Farmonov_HB', help_text='Telegram manzilingizni kiriting', verbose_name='telegram')),
                ('instagram', models.URLField(default='https://me.@Farmonov_HB', help_text='instagram manzilingizni kiriting', verbose_name='instagram')),
                ('github', models.URLField(default='https://me.@Farmonov_HB', help_text='github manzilingizni kiriting', verbose_name='GitHub')),
                ('facebook', models.URLField(default='https://me.@Farmonov_HB', help_text='facebook manzilingizni kiriting', verbose_name='Facebook')),
                ('youtube', models.URLField(default='https://me.@Farmonov_HB', help_text='youtebe manzilingizni kiriting', verbose_name='Facebook')),
                ('twitter', models.URLField(default='https://me.@Farmonov_HB', help_text='twitter manzilingizni kiriting', verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'Social links',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
