# Generated by Django 4.1.3 on 2022-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio_project',
            name='images',
            field=models.ImageField(help_text='loyiha rasmini yuklang', upload_to='loyiha_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='facebook',
            field=models.URLField(default='', help_text='facebook manzilingizni kiriting', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='github',
            field=models.URLField(default='', help_text='github manzilingizni kiriting', verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='instagram',
            field=models.URLField(default='', help_text='instagram manzilingizni kiriting', verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='telegram',
            field=models.URLField(default='', help_text='Telegram manzilingizni kiriting', verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='twitter',
            field=models.URLField(default='', help_text='twitter manzilingizni kiriting', verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='youtube',
            field=models.URLField(default='', help_text='youtebe manzilingizni kiriting', verbose_name='youtube'),
        ),
    ]
